version: '3'

networks:
  lubycash:
    external: true
services:
  lubycash-adonis:
    build:
      context: .
    ports:
      - '3333:3333'
    environment:
      MYSQL_HOST: 'mysql'
      MYSQL_PORT: '3306'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_DB_NAME: 'lubycash_db'
    volumes:
      - lubycash-adonis:/usr/app
    networks:
      - lubycash
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lubycash_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    command:
      [
        mysqld,
        --default-authentication-plugin=mysql_native_password,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
        --bind-address=0.0.0.0,
      ]

    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - lubycash

volumes:
  db-data:
  lubycash-adonis: